service: leaderboard-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    USER_POOL_ID: ${env:USER_POOL_ID}
    USER_POOL_DOMAIN: ${env:USER_POOL_DOMAIN}

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: api/{proxy+}
          method: ANY

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
