export const env = {

  VITE_COGNITO_CLIENT_ID: import.meta.env.VITE_COGNITO_CLIENT_ID,
  VITE_COGNITO_REDIRECT_URI: import.meta.env.VITE_COGNITO_REDIRECT_URI,
  VITE_COGNITO_DOMAIN: import.meta.env.VITE_COGNITO_DOMAIN,
  VITE_API_URL: import.meta.env.VITE_API_URL,
  VITE_COGNITO_AUTHORITY: import.meta.env.VITE_COGNITO_AUTHORITY,

  /*
  VITE_COGNITO_CLIENT_ID: process.env.VITE_COGNITO_CLIENT_ID || '',
  VITE_COGNITO_REDIRECT_URI: process.env.VITE_COGNITO_REDIRECT_URI || '',
  VITE_COGNITO_DOMAIN: process.env.VITE_COGNITO_DOMAIN || '',
  VITE_API_URL: process.env.VITE_API_URL || '',

   */
};
